# Generated by Django 4.0.1 on 2022-02-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedRoom',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('date_n', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('date_arrive', models.DateTimeField()),
                ('date_depart', models.DateTimeField()),
                ('db_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.bedroom')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.user')),
            ],
        ),
    ]
