# Generated by Django 4.0.1 on 2022-02-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='price',
            field=models.IntegerField(default=10000),
        ),
    ]
